CREATE TABLE `temp_banco` (
  `idBanco` INT NOT NULL AUTO_INCREMENT,
  `nome`    VARCHAR(254) NOT NULL,
  `numero`  INT NOT NULL,
  `website` VARCHAR(254) DEFAULT NULL,
  PRIMARY KEY (`idbanco`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO temp_banco (numero, nome) VALUES
(1,'Banco do Brasil S.A.'),
(3,'Banco da Amazônia S.A.'),
(4,'Banco do Nordeste do Brasil S.A.'),
(7,'Banco Nacional de Desenvolvimento Econômico e Social'),
(12,'Banco INBURSA de Investimentos S.A.'),
(14,'Natixis Brasil S.A. Banco Múltiplo'),
(17,'BNY Mellon Banco S.A.'),
(18,'Banco Tricury S.A.'),
(21,'BANESTES S.A. Banco do Estado do Espírito Santo'),
(24,'Banco BANDEPE S.A.'),
(25,'Banco Alfa S.A.'),
(29,'Banco Itaú BMG Consignado S.A.'),
(33,'Banco Santander (Brasil) S.A.'),
(36,'Banco Bradesco BBI S.A.'),
(37,'Banco do Estado do Pará S.A.'),
(40,'Banco Cargill S.A.'),
(41,'Banco do Estado do Rio Grande do Sul S.A.'),
(47,'Banco do Estado de Sergipe S.A.'),
(62,'Hipercard Banco Múltiplo S.A.'),
(63,'Banco Bradescard S.A.'),
(64,'Goldman Sachs do Brasil Banco Múltiplo S.A.'),
(65,'Banco Andbank (Brasil) S.A.'),
(66,'Banco Morgan Stanley S.A.'),
(69,'Banco BPN Brasil S.A.'),
(70,'BRB - Banco de Brasília S.A.'),
(74,'Banco J. Safra S.A.'),
(75,'Banco ABN AMRO S.A.'),
(76,'Banco KDB S.A.'),
(77,'Banco Intermedium S.A.'),
(78,'Haitong Banco de Investimento do Brasil S.A.'),
(79,'Banco Original do Agronegócio S.A.'),
(81,'BBN Banco Brasileiro de Negócios S.A.'),
(82,'Banco Topázio S.A.'),
(83,'Banco da China Brasil S.A.'),
(84,'Uniprime Norte do Paraná - Coop de Economia e Crédito Mútuo dos Médicos'),
(88,'Banco Randon S.A.'),
(92,'Brickell S.A. Crédito'),
(94,'Banco Petra S.A.'),
(95,'Banco Confidence de Câmbio S.A.'),
(96,'Banco BM&FBOVESPA de Serviços de Liquidação e Custódia S.A'),
(97,'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.'),
(104,'Caixa Econômica Federal'),
(107,'Banco BBM S.A.'),
(118,'Standard Chartered Bank (Brasil) S/A–Bco Invest.'),
(119,'Banco Western Union do Brasil S.A.'),
(120,'Banco Rodobens S.A.'),
(121,'Banco Gerador S.A.'),
(122,'Banco Bradesco BERJ S.A.'),
(124,'Banco Woori Bank do Brasil S.A.'),
(125,'Brasil Plural S.A. - Banco Múltiplo'),
(128,'MS Bank S.A. Banco de Câmbio'),
(129,'UBS Brasil Banco de Investimento S.A.'),
(132,'ICBC do Brasil Banco Múltiplo S.A.'),
(136,'CONFEDERACAO NACIONAL DAS COOPERATIVAS CENTRAIS UNICREDS'),
(169,'Banco Bonsucesso Consignado S.A.'),
(184,'Banco Itaú BBA S.A.'),
(204,'Banco Bradesco Cartões S.A.'),
(208,'Banco BTG Pactual S.A.'),
(212,'Banco Original S.A.'),
(213,'Banco Arbi S.A.'),
(217,'Banco John Deere S.A.'),
(218,'Banco Bonsucesso S.A.'),
(222,'Banco Credit Agricole Brasil S.A.'),
(224,'Banco Fibra S.A.'),
(233,'Banco Cifra S.A.'),
(237,'Banco Bradesco S.A.'),
(241,'Banco Clássico S.A.'),
(243,'Banco Máxima S.A.'),
(246,'Banco ABC Brasil S.A.'),
(248,'Banco Boavista Interatlântico S.A.'),
(249,'Banco Investcred Unibanco S.A.'),
(250,'BCV - Banco de Crédito e Varejo S.A.'),
(254,'Paraná Banco S.A.'),
(263,'Banco Cacique S.A.'),
(265,'Banco Fator S.A.'),
(266,'Banco Cédula S.A.'),
(300,'Banco de La Nacion Argentina'),
(318,'Banco BMG S.A.'),
(320,'China Construction Bank (Brasil) Banco Múltiplo S.A.'),
(341,'Itaú Unibanco S.A.'),
(366,'Banco Société Générale Brasil S.A.'),
(370,'Banco Mizuho do Brasil S.A.'),
(376,'Banco J. P. Morgan S.A.'),
(389,'Banco Mercantil do Brasil S.A.'),
(394,'Banco Bradesco Financiamentos S.A.'),
(399,'HSBC Bank Brasil S.A. - Banco Múltiplo'),
(412,'Banco Capital S.A.'),
(422,'Banco Safra S.A.'),
(456,'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.'),
(464,'Banco Sumitomo Mitsui Brasileiro S.A.'),
(473,'Banco Caixa Geral - Brasil S.A.'),
(477,'Citibank N.A.'),
(479,'Banco ItauBank S.A'),
(487,'Deutsche Bank S.A. - Banco Alemão'),
(488,'JPMorgan Chase Bank National Association'),
(492,'ING Bank N.V.'),
(494,'Banco de La Republica Oriental del Uruguay'),
(495,'Banco de La Provincia de Buenos Aires'),
(505,'Banco Credit Suisse (Brasil) S.A.'),
(600,'Banco Luso Brasileiro S.A.'),
(604,'Banco Industrial do Brasil S.A.'),
(610,'Banco VR S.A.'),
(611,'Banco Paulista S.A.'),
(612,'Banco Guanabara S.A.'),
(613,'Banco Pecúnia S.A.'),
(623,'Banco PAN S.A.'),
(626,'Banco Ficsa S.A.'),
(630,'Banco Intercap S.A.'),
(633,'Banco Rendimento S.A.'),
(634,'Banco Triângulo S.A.'),
(637,'Banco Sofisa S.A.'),
(641,'Banco Alvorada S.A.'),
(643,'Banco Pine S.A.'),
(652,'Itaú Unibanco Holding S.A.'),
(653,'Banco Indusval S.A.'),
(654,'Banco A.J.Renner S.A.'),
(655,'Banco Votorantim S.A.'),
(658,'Banco Porto Real de Investimentos S.A.'),
(707,'Banco Daycoval S.A.'),
(712,'Banco Ourinvest S.A.'),
(719,'Banif-Banco Internacional do Funchal (Brasil)S.A.'),
(720,'Banco Maxinvest S.A.'),
(735,'Banco Pottencial S.A.'),
(739,'Banco Cetelem S.A.'),
(740,'Banco Barclays S.A.'),
(741,'Banco Ribeirão Preto S.A.'),
(743,'Banco Semear S.A.'),
(745,'Banco Citibank S.A.'),
(746,'Banco Modal S.A.'),
(747,'Banco Rabobank International Brasil S.A.'),
(748,'Banco Cooperativo Sicredi S.A.'),
(751,'Scotiabank Brasil S.A. Banco Múltiplo'),
(752,'Banco BNP Paribas Brasil S.A.'),
(753,'Novo Banco Continental S.A. - Banco Múltiplo'),
(755,'Bank of America Merrill Lynch Banco Múltiplo S.A.'),
(756,'Banco Cooperativo do Brasil S.A. - BANCOOB'),
(757,'Banco KEB HANA do Brasil S.A.');

insert into banco
select null,
       UPPER(nome),
       numero,
       null
  from temp_banco tb
 where not exists(select 1 from banco b where tb.numero = b.numero);

DROP TABLE temp_banco;