USE pp_06895434000183;

DROP TABLE banco;
DROP TABLE tipo_conta;
DROP TABLE plano_conta;

CREATE TABLE `banco` (
  `idBanco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(254) NOT NULL,
  `numero` INT NOT NULL,
  `website` VARCHAR(254) DEFAULT NULL,
  PRIMARY KEY (`idbanco`) ,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8;

CREATE TABLE `tipo_conta` (
  `idTipoConta` INT NOT NULL AUTO_INCREMENT,
  `categoria` INT NOT NULL,
  `descricao` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`idTipoConta`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8;

CREATE TABLE `plano_conta` (
  `idPlanoConta` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `codigo` INT NOT NULL,
  `nome` VARCHAR(254) NOT NULL,
  `grupo` INT DEFAULT NULL,
  PRIMARY KEY (`idPlanoConta`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8;

 











